services:
  discord-bot:
    build: .
    container_name: worldbuffs-bot
    restart: always
    env_file: .env
    volumes:
      - ./google-service-account.json:/app/google-service-account.json:ro
      - ./processed_messages.json:/app/processed_messages.json